---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: myapp-test
        image: chandrag139/testapp:{"$BUILD_NUMBER"}
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: test
spec:
  selector:
    app: test
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 32000

